import type { FormDetail, FormField } from "./types";

/**
 * 재외동포(F-4) 통합신청서 — 16개 빈칸 목업.
 *
 * 서식 상세 API가 붙기 전까지 쓰는 임시 데이터이며, 응답 형태를 그대로 흉내낸다.
 * 5종 카드 타입(choice / number / text / sign / photo)이 모두 최소 하나씩 들어 있다.
 *   choice 2 · number 3 · text 9 · sign 1 · photo 1
 *
 * anchor 는 A4 1페이지(794×1123) 기준 위치를 0~1 비율로 환산한 값이다.
 */
export const F4_FIELDS: FormField[] = [
  {
    id: "select",
    type: "choice",
    label: "신청/신고 선택",
    page: 1,
    hint: "하나만 선택",
    question: "먼저, 어떤 신청/신고를 하시나요? 아래에서 하나만 골라 주세요.",
    options: [
      "외국국적동포 국내거소신고",
      "국내거소 이전신고",
      "국내거소신고증 재발급",
      "체류기간 연장허가",
      "체류자격 변경허가",
      "체류자격 부여",
    ],
    example: "외국국적동포 국내거소신고",
    anchor: { page: 1, x: 0.055, y: 0.142, w: 0.55, h: 0.098 },
  },
  {
    id: "photo",
    type: "photo",
    label: "PHOTO 여권용 사진",
    page: 1,
    hint: "촬영일부터 6개월 이내",
    question: "여권용 사진(35㎜×45㎜)을 첨부해 주세요.",
    example: "(사진 첨부됨)",
    anchor: { page: 1, x: 0.63, y: 0.142, w: 0.315, h: 0.098 },
  },
  {
    id: "surname",
    type: "text",
    label: "성 (Surname)",
    page: 1,
    hint: "여권 영문 표기와 동일하게",
    question: "여권에 적힌 영문 성(Surname)을 입력해 주세요.",
    placeholder: "예) HONG",
    example: "HONG",
    anchor: { page: 1, x: 0.22, y: 0.272, w: 0.22, h: 0.038 },
  },
  {
    id: "given",
    type: "text",
    label: "명 (Given names)",
    page: 1,
    hint: "여권 영문 표기와 동일하게",
    question: "이번엔 영문 이름(Given names)이에요. 여권 그대로 적어 주세요.",
    placeholder: "예) GILDONG",
    example: "GILDONG",
    anchor: { page: 1, x: 0.44, y: 0.272, w: 0.22, h: 0.038 },
  },
  {
    id: "krName",
    type: "text",
    label: "한글 성명",
    page: 1,
    hint: "한글로 기재",
    question: "한글 성명을 입력해 주세요. 모르시면 비워 두셔도 괜찮아요.",
    placeholder: "예) 홍길동",
    example: "홍길동",
    anchor: { page: 1, x: 0.66, y: 0.272, w: 0.285, h: 0.038 },
  },
  {
    id: "birth",
    type: "number",
    label: "생년월일",
    page: 1,
    mask: "####-##-##",
    hint: "yyyy-mm-dd",
    question: "생년월일을 숫자로 입력해 주세요. (예: 1988-03-14)",
    example: "1988-03-14",
    anchor: { page: 1, x: 0.22, y: 0.324, w: 0.28, h: 0.038 },
  },
  {
    id: "sex",
    type: "choice",
    label: "성별",
    page: 1,
    hint: "하나만 선택",
    question: "성별을 선택해 주세요.",
    options: ["남 M", "여 F"],
    example: "남 M",
    anchor: { page: 1, x: 0.66, y: 0.324, w: 0.285, h: 0.038 },
  },
  {
    id: "nationality",
    type: "text",
    label: "국적",
    page: 1,
    hint: "현재 국적",
    question: "현재 국적을 입력해 주세요.",
    placeholder: "예) 미국 (USA)",
    example: "미국 (USA)",
    anchor: { page: 1, x: 0.22, y: 0.376, w: 0.725, h: 0.038 },
  },
  {
    id: "regNo",
    type: "number",
    label: "외국인등록번호(국내거소신고번호)",
    page: 1,
    mask: "######-#######",
    hint: "13자리",
    question: "외국인등록번호(국내거소신고번호) 13자리를 입력해 주세요. 없으면 건너뛰셔도 돼요.",
    example: "880314-5123456",
    anchor: { page: 1, x: 0.33, y: 0.428, w: 0.615, h: 0.038 },
  },
  {
    id: "passport",
    type: "text",
    label: "여권번호",
    page: 1,
    hint: "여권에 기재된 번호",
    question: "여권번호를 입력해 주세요.",
    placeholder: "예) M12345678",
    example: "M12345678",
    anchor: { page: 1, x: 0.22, y: 0.48, w: 0.25, h: 0.038 },
  },
  {
    id: "passIssue",
    type: "number",
    label: "여권 발급일자",
    page: 1,
    mask: "####-##-##",
    hint: "yyyy-mm-dd",
    question: "여권 발급일자를 입력해 주세요. (예: 2021-05-02)",
    example: "2021-05-02",
    anchor: { page: 1, x: 0.66, y: 0.48, w: 0.285, h: 0.038 },
  },
  {
    id: "address",
    type: "text",
    label: "대한민국 안의 거소",
    page: 1,
    hint: "국내 거주지 주소",
    question: "대한민국 안의 거소, 즉 국내 거주지 주소를 입력해 주세요.",
    placeholder: "예) 서울특별시 서초구 반포대로 58",
    aiEnabled: true,
    aiPlaceholder: "예: 서울 강남구 역삼동에 있는 오피스텔에 살아요. 근처에 강남역이 있어요.",
    example: "서울특별시 서초구 반포대로 58",
    anchor: { page: 1, x: 0.22, y: 0.542, w: 0.725, h: 0.038 },
  },
  {
    id: "phone",
    type: "text",
    label: "휴대전화",
    page: 1,
    hint: "연락 가능한 번호",
    question: "연락 가능한 휴대전화 번호를 입력해 주세요.",
    placeholder: "예) 010-1234-5678",
    example: "010-1234-5678",
    anchor: { page: 1, x: 0.22, y: 0.6, w: 0.725, h: 0.038 },
  },
  {
    id: "job",
    type: "text",
    label: "직업",
    page: 1,
    hint: "현재 직업",
    question: "현재 직업을 입력해 주세요.",
    placeholder: "예) 소프트웨어 엔지니어",
    aiEnabled: true,
    aiPlaceholder: "예: IT 회사에서 앱 만드는 일 해요",
    example: "소프트웨어 엔지니어",
    anchor: { page: 1, x: 0.22, y: 0.652, w: 0.725, h: 0.038 },
  },
  {
    id: "account",
    type: "text",
    label: "반환용 계좌번호",
    page: 1,
    optional: true,
    hint: "발급 신청 시에만 · 선택",
    question: "반환용 계좌번호예요. 해당 없으면 건너뛰셔도 괜찮아요.",
    placeholder: "예) 국민은행 123456-04-567890",
    aiEnabled: true,
    aiPlaceholder: "예: 국민은행 쓰고 있어요. 계좌번호 뒷자리가 567890이에요",
    example: "국민은행 123456-04-567890",
    anchor: { page: 1, x: 0.22, y: 0.704, w: 0.725, h: 0.038 },
  },
  {
    id: "sign",
    type: "sign",
    label: "서명",
    page: 1,
    hint: "신청인 서명 또는 인",
    question: "마지막으로 신청인 서명이에요. 아래에 직접 서명해 주세요.",
    example: "홍길동",
    anchor: { page: 1, x: 0.58, y: 0.855, w: 0.3, h: 0.05 },
  },
];

export const F4_FORM: FormDetail = {
  id: "f4-application",
  title: "재외동포(F-4) 통합신청서",
  category: "외국인 비자 서식",
  totalPages: 1,
  fields: F4_FIELDS,
};
